<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPBQLgJw\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPBQLgJw/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPBQLgJw.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPBQLgJw\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerPBQLgJw\srcDevDebugProjectContainer([
    'container.build_hash' => 'PBQLgJw',
    'container.build_id' => '4a0d5bdf',
    'container.build_time' => 1573564899,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPBQLgJw');
